server:
  port: 8082

spring:
  application:
    name: spring-eureka-client
  profiles:
    active: development
  main:
    banner-mode: off
  config:
    import: optional:configserver:-
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        serviceId: spring-remote-config

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    appname: ${spring.application.name}
    hostname: ${DOMAIN_NAME:localhost}
    preferIpAddress: true
    #    lease-renewal-interval-in-seconds: 1
    #    lease-expiration-duration-in-seconds: 2
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

user:
  role: Guest

---
spring:
  cloud:
    config:
      label: heroku
  profiles: heroku

eureka:
  instance:
    preferIpAddress: false
    nonSecurePort: 80
    statusPageUrl: http://${eureka.instance.hostname}:${eureka.instance.nonSecurePort}/actuator/info
    healthCheckUrl: http://${eureka.instance.hostname}:${eureka.instance.nonSecurePort}/actuator/health